language: haskell
install:
  - npm install -g elm
  - npm install -g elm-test
  - elm-package install -y
before_script:
  - cd tests
  - elm-make --yes --output ../raw-test.js Tests.elm
  - cd ..
script: 
  - elm-test
